# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'New_FinalProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for New_FinalProject
  pod 'SwiftyJSON'
  pod 'SwiftSpinner'
  pod 'PromiseKit'
  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'

end
