# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'currencyConver_2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for currencyConver_2
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod "SwiftSpinner"

end
